### ISSUE TITLE
inefficiency of jwk to pem conversion causes performance issues

### ISSUE THREAD

**Issue by marcin-iwanow** [nearform/get-jwks#297] opened 2024-07-17 12:24 UTC
In our setup, we verify our jwt tokens on an authoriser, which we deploy on AWS as a lambda. We tried to switch to `get-jwks` but with the config we used till now (128MB of memory) we observed that it's extremely slow: verifying a jwt signed with a EC key was taking 6s on average (!!!) if the key hasn't yet been cached. We traced it back to inefficient performance of the `jwk-to-pem` package, which was responsible for almost the entire processing time.

I'd suggest to change it, maybe just getting rid of the dependency at all (like `jwks-rsa` does)? Anyways it's stale for like 2 years now.

**Comment by simoneb** [comment] 2024-07-17 12:50
Thanks for reporting, what were you using in your previous flow to do the verification and which didn't exhibit any performance issues?

**Comment by marcin-iwanow** [comment] 2024-07-17 13:08
jwks-rsa, and we stay with it for now (after realising that the `rsa` in the name is a false flag, and they also support EC 😄 )

**Comment by imdavidmin** [comment] 2024-07-19 08:02
I might not have the full context here, out of curiosity why do you think the package takes 6s to do this task? It's not related to cold starts on Lambda I assume, and the package running locally would also take that long to process? 

I've used [jose](https://www.npmjs.com/package/jose) before for all related JWT stuff, and have also used the web crypto API to do parsing / reading. What's the proposed solution for now if we want to get rid of `jwk-to-pem`?

**Comment by simoneb** [comment] 2024-07-19 09:00
@imdavidmin it seems @marcin-iwanow is suggesting to switch to `jwks-rsa`. Shall we do a quick experimento to see if we notice any performance boost by doing the switch?

**Comment by marcin-iwanow** [comment] 2024-07-19 09:06
well, `jwks-rsa` is rather an alternative to `get-jwks` then to `jwk-to-pem`. I am not sure what they use for the conversion. And regarding the performance, locally I couldn't really reproduce (I was running the lambda in serverless offline and couldn't limit resources). But on aws it struggles a lot with the low setup: I mentioned 128MB of memory (the minimum possible) but it also comes with the cpu config as long as I know, and I expect some cpu expensive operation that can be the bottleneck. For RSA the conversion was slow but not tragic (1.5s?) but for EC it was just not acceptable

**Comment by imdavidmin** [comment] 2024-07-19 09:36
I see, so the proposal is to deprecate `get-jwks` altogether and use a pre-existing library for those needs? In which case, perhaps we'd need to figure out if an alternative we use instead covers all our existing use cases for `get-jwks`

There's a good comparison of JWT libraries [here ](https://jwt.io/libraries)from jwt.io

**Comment by imdavidmin** [comment] 2024-07-22 15:45
Awaiting response from IT services for AWS environment, but for now adding in performance tests. Results so far show the normal success path (tests from `getJwk.spec.js`) are running at sub 25ms (11ms on my local machine).

**Comment by imdavidmin** [comment] 2024-07-23 08:19
@marcin-iwanow To diagnose this issue further, did you already test both RSA and EC keys on your local machine with good performance, but the same keys on your Lambda instance was taking very long, with 128MB memory? I'd like to be able to reproduce the issue to debug this further. Thanks

**Comment by marcin-iwanow** [comment] 2024-07-23 09:35
on my local machine I haven't seen any significant differences, but also haven't profiled it carefully. (btw note that in your tests you use only RSA keys if I am not mistaken, maybe makes sense to add other ones also, but it's at your discretion ofc :) )

**Comment by simoneb** [comment] 2024-07-23 09:37
@marcin-iwanow can you provide a repro please?

**Comment by simoneb** [comment] 2024-07-29 09:33
Closing as we're missing a repro and we're unable to reproduce. Feel free to reopen in case you can reproduce the issue. Thanks @imdavidmin for looking into it.

**Closed by simoneb** 2024-07-29 09:33 UTC
